singleQuote: true

# # TODO: better custom ordering
# importOrder: ['^lit(.*)$', '^@jsfe/(.*)$', '^@(.*)$', '^[./]']
# importOrderSeparation: true
# importOrderSortSpecifiers: true
# importOrderParserPlugins: ['typescript', 'decorators-legacy']
